[package]
name = "add"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.component]
package = "component:add"

[package.metadata.component.dependencies]
