package legion:tools;

world tools {
	record tools-error {
		message: string
	}
    record encode-config {
        generate-dwarf: bool
    }
    record decode-config {
        skeleton-only: bool,
        name-unnamed: bool,
        fold-instructions: bool
    }
    export encode-wasm: func(input: string, config: encode-config) -> result<list<u8>, tools-error>;
    export decode-wasm: func(input: list<u8>, config: decode-config) -> result<string, tools-error>;
}
